name: bilibili-daily-task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '10 21 * * *'
    # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分

jobs:
  run-bilibili-tool:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Run
      env:
        userId: ${{433527147}}
        sessData: ${{0b154cdd%2C1738974364%2Ccee6f%2A81CjCGp6-9MTiK3HVc4efxhYFBxHCNtXqnxsitgUmvuYfBm4RCwXt-JK6BbyK1pk8R_igSVmUxd0FsN0dqSTk0TkZ5bnNLREM1UVIxYk84TjBLQVRaWWhWMlhmTDZCZ1NlM0JGMlhhUHZCZzNNUFc2YkM1YjdsdC1PY3RTVEg4MmtITjhOMERVaXlRIIEC}}
        biliJct: ${{ff37c81619e60fca18a774d946897173}}
        otherConfigs: ${{secrets.OTHERCONFIGS}}
      run: dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${userId} -sessData=${sessData} -biliJct=${biliJct} -closeConsoleWhenEnd=1 ${otherConfigs}
